In [6]:
#Q1
def my_tip_calc(bill, party):
    # write your function code here
    if party < 6:
        tips = 0.15 * bill
    elif 6 <=party < 8:
        tips = 0.18 * bill
    elif 8 <= party < 11:
        tips = 0.2 * bill
    elif party >= 11:
        tips = 0.25 * bill
    return tips

In [7]:
# t = 16.3935
t = my_tip_calc(109.29,3) 
print(t)

16.3935


In [8]:
# t = 19.6722
t = my_tip_calc(109.29,7) 
print(t)

19.6722


In [9]:
# t = 21.8580
t = my_tip_calc(109.29,9)
print(t)

21.858000000000004


In [10]:
# t = 27.3225
t = my_tip_calc(109.29,12)
print(t)

27.3225


In [16]:
# Q2
import numpy as np
def my_mult_operation(a,b,operation):
    # write your function code here
    if operation == 'plus':
        out = a + b
    elif operation == 'minus':
        out = a - b
    elif operation == 'mult':
        out = a * b
    elif operation == 'div':
        out = a / b
    elif operation == 'pow':
        out = a ** b
    
    return out

In [17]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

In [18]:
# Output: [3,5,7,9]
my_mult_operation(x,y,'plus')

array([3, 5, 7, 9])

In [19]:
# Output: [-1,-1,-1,-1]
my_mult_operation(x,y,'minus')

array([-1, -1, -1, -1])

In [20]:
# Output: [2,6,12,20]
my_mult_operation(x,y,'mult')

array([ 2,  6, 12, 20])

In [21]:
# Output: [0.5,0.66666667,0.75,0.8]
my_mult_operation(x,y,'div')

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [22]:
# Output: [1,8,81,1024]
my_mult_operation(x,y,'pow')

array([   1,    8,   81, 1024])

In [76]:
#Q3 
def my_inside_triangle(x,y):
    # write your function code here
    x1, y1 = 0, 1
    x2, y2, = 0, 0
    x3, y3 = 1, 0

    area = abs((x1*(y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)) / 2)
    alpha = abs((x*( y1 - y3) + x1 * (y3 - y) + x3 * (y - y1)) / 2)
    beta = abs((x * (y2 - y3) + x2 * (y3 - y) + x3 * (y - y2)) / 2)
    gamma = abs((x * (y1 - y2) + x1 * (y2 - y) + x2 * (y - y1)) / 2)

    if alpha + beta + gamma == area and (alpha > 0 and beta > 0 and gamma > 0):
        position = 'inside'
    elif alpha + beta + gamma == area and (alpha == 0 or beta == 0 or gamma == 0):
        position = 'border'
    elif alpha + beta + gamma != area:
        position = 'outside'
    return position

In [77]:
# Output: 'border'
my_inside_triangle(.5,.5)

'border'

In [78]:
# Output: 'inside'
my_inside_triangle(.25,.25)

'inside'

In [79]:
# Output: 'outside'
my_inside_triangle(5,5)

'outside'

In [110]:
#Q4
def my_make_size10(x):
    # write your function code here
    x = list(x)
    if len(x) >= 10:
        size10 = x[:10]
    else:
        size10 = x + [0] * (10 - len(x))
    return size10

In [111]:
# Output: [1,2,0,0,0,0,0,0,0,0]
my_make_size10(range(1,2)) # doubt

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [112]:
# Output: [1,2,3,4,5,6,7,8,9,10]
my_make_size10(range(1,15))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [113]:
# Output: [3,6,13,4,0,0,0,0,0,0]
# my_make_size10(5,5)
# doubts

In [120]:
#Q5
def my_make_size10(x):
    # write your function code here
    x = list(x[:10])
    return x + [0] * (10 - len(x))

In [121]:
my_make_size10(range(1,2)) # doubt

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [122]:
my_make_size10(range(1,15))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [124]:
#Q6
def my_letter_grader(percent):
    # write your function code here
    if percent >= 97:
        grade = 'A+'
    elif 93 <= percent < 97:
        grade = 'A'
    elif 90 <= percent < 93:
        grade = 'A-'
    elif 87 <= percent < 90:
        grade = 'B+'
    elif 83 <= percent < 87:
        grade = 'B'
    elif 80 <= percent < 83:
        grade = 'B-'
    elif 77 <= percent < 80:
        grade = 'C+'
    elif 73 <= percent < 77:
        grade = 'C'
    elif 70 <= percent < 73:
        grade = 'C-'
    elif 67 <= percent < 70:
        grade = 'D+'
    elif 63 <= percent < 67:
        grade = 'D'
    elif 60 <= percent < 63:
        grade = 'D-'
    elif percent < 60:
        grade = 'F'
    return grade

In [125]:
# Output: 'A+'
my_letter_grader(97)

'A+'

In [126]:
# Output: 'B'
my_letter_grader(84)

'B'

In [127]:
#Q7

In [128]:
def my_nuke_alarm(s1,s2,s3):
    # write your function code here
    if abs(s1 - s2) >  10 or abs(s2 - s3) > 10 or abs(s3 - s1) > 10:
        response = 'alarm!'
    else:
        response = 'normal'
    return response

In [129]:
#Output: 'normal'
my_nuke_alarm(94,96,90)

'normal'

In [130]:
#Output: 'alarm!'
my_nuke_alarm(94,96,80)

'alarm!'

In [131]:
#Output: 'normal'
my_nuke_alarm(100,96,90)

'normal'

In [132]:
#Q8
import cmath

def my_n_roots(a,b,c):
    # write your function code here
    if b**2 > 4*a*c:
        n_roots = 2
    elif b**2 == 4*a*c:
        n_roots = 1
    elif b**2 < 4*a*c:
        n_roots = -2
    r = []
    if n_roots == -2 or n_roots == 2:
        r1 = (-b + cmath.sqrt(b**2 - 4*a*c)) / (2*a)
        r.append(r1)
        r2 = (-b - cmath.sqrt(b**2 - 4*a*c)) / (2*a)
        r.append(r2)
    elif n_roots == 1:
        r.append(-b / (2*a))
    return n_roots, r

In [133]:
# Output: n_roots = 2, r = [3, -3]
n_roots, r = my_n_roots(1,0,-9)
print(n_roots, r)

2 [(3+0j), (-3+0j)]


In [134]:
# Output: n_roots = -2, r = [-0.6667 + 1.1055i, -0.6667 - 1.1055i]
my_n_roots(3,4,5)

(-2,
 [(-0.6666666666666666+1.1055415967851332j),
  (-0.6666666666666666-1.1055415967851332j)])

In [135]:
# Output: n_roots = 1, r = [1]
my_n_roots(2,4,2)

(1, [-1.0])

In [136]:
#Q9
def my_split_function(f,g,a,b,x):
    
    if x<=a:
        return float(f(x))
    elif x>=b:
        return float(g(x))
    else:
        return 0

In [137]:
# Output: 2.713
my_split_function(np.exp,np.sin,2,4,1)

2.718281828459045

In [138]:
# Output: 0
my_split_function(np.exp,np.sin,2,4,3)

0

In [139]:
# Output: -0.9589
my_split_function(np.exp,np.sin,2,4,5)

-0.9589242746631385