In [1]:
#Q1

In [2]:
x = 2
y = 3

In [3]:
del x

In [4]:
x

NameError: name 'x' is not defined

In [5]:
#Q1
import math

x = 10
y = 3

u = x + y
v = x*y
w = x/y
z = math.sin(x)
r = 8*math.sin(x) 
s = 5*math.sin(x*y)
p = x**y

In [6]:
%whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' from '/opt<...>h.cpython-313-darwin.so'>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


In [7]:
#Q2
S = '123'
N = float(S)
print(type(S))
print(type(N))

<class 'str'>
<class 'float'>


In [9]:
#Q3
s1 = "HELLO"
s2 = "hello"
s1 == s2

False

In [10]:
s1.lower() == s2

True

In [11]:
s1 == s2.upper()

True

In [16]:
#Q4
text1 = "Engineering"
text2 = "Book"

print(f"The word '{text1}' has {len(text1)} letters.")
print(f"The word '{text2}' has {len(text2)} letters.")

The word 'Engineering' has 11 letters.
The word 'Book' has 4 letters.


In [18]:
#Q5
s = "Python is great!"
"Python" in s

True

In [27]:
#Q6
s.index('g')
s[10:-1]

'great'

In [29]:
#Q7
list_a = [1, 8, 9, 15] 
list_a.insert(1, 2)
list_a.append(4)
list_a

[1, 2, 8, 9, 15, 4]

In [31]:
#Q8
list_a.sort()
list_a

[1, 2, 4, 8, 9, 15]

In [32]:
#Q9
s = "Python is great!"
list_b = list(s)
print(list_b)

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']


In [35]:
#Q10
tuple_a = ('One', 1)
tuple_a

('One', 1)

In [36]:
#Q11
tuple_a[1]

1

In [37]:
#Q12
u =  (2, 3, 2, 3, 1, 2, 5)
print(set(u))

{1, 2, 3, 5}


In [39]:
#Q13

set_a = {2, 3, 2}
set_b = {1, 2, 3}

print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


In [40]:
#Q14

dict_1 = {}
dict_1['A'] = 'a'
dict_1['B'] = 'b'
dict_1['C'] = 'c'

dict_1.keys()

dict_keys(['A', 'B', 'C'])

In [41]:
#Q15
"B" in dict_1

True

In [45]:
#Q16

import numpy as np
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])

u = x + y
v = x*y
w = x/y
z = np.sin(x)
r = 8*np.sin(x) 
s = 5*np.sin(x*y)
p = x**y
print(u)
print(v)
print(w)
print(z)
print(r)
print(s)
print(p)

[ 3  7  7  3 11  7]
[ 2 12 12  2 18 12]
[0.5        1.33333333 0.75       2.         4.5        1.33333333]
[ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]
[ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]
[ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]
[ 1 64 81  2 81 64]


In [46]:
#Q17
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [47]:
#Q18
array_a = np.array([-1, 0, 1, 2, 0, 3])
y = array_a[array_a > 0]
y

array([1, 2, 3])

In [48]:
#Q19
y = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

In [54]:
#Q20
zero = np.zeros((2,4))

In [55]:
#Q21
zero[:, 1] = 1
zero

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [56]:
%whos

Variable   Type       Data/Info
-------------------------------
N          float      123.0
S          str        123
array_a    ndarray    6: 6 elems, type `int64`, 48 bytes
dict_1     dict       n=3
list_a     list       n=6
list_b     list       n=16
math       module     <module 'math' from '/opt<...>h.cpython-313-darwin.so'>
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
p          ndarray    6: 6 elems, type `int64`, 48 bytes
r          ndarray    6: 6 elems, type `float64`, 48 bytes
s          ndarray    6: 6 elems, type `float64`, 48 bytes
s1         str        HELLO
s2         str        hello
set_a      set        {2, 3}
set_b      set        {1, 2, 3}
text1      str        Engineering
text2      str        Book
tuple_a    tuple      n=2
u          ndarray    6: 6 elems, type `int64`, 48 bytes
v          ndarray    6: 6 elems, type `int64`, 48 bytes
w          ndarray    6: 6 elems, type `float64`, 48 bytes
x          ndarray    6: 6 elems, type

In [58]:
#Q22
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [59]:
%whos

Interactive namespace is empty.
