In [1]:
x = 1
x

1

In [2]:
y = 2
y

2

In [4]:
y * 3

6

In [5]:
%whos

Variable   Type    Data/Info
----------------------------
x          int     1
y          int     2


In [6]:
x = x + 1
x

2

In [7]:
x = 1
y = x + 1
x = 2
y

2

In [8]:
del x

In [9]:
%whos

Variable   Type    Data/Info
----------------------------
y          int     2


In [10]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [11]:
%whos

Interactive namespace is empty.


In [12]:
# Strings
print("I love python")

I love python


In [13]:
s = "S"
w = "Hello world"

In [14]:
type(s)

str

In [15]:
type(w)

str

In [16]:
s = " "
type(s)

str

In [17]:
len(w)

11

In [18]:
w[6]

'w'

In [19]:
w[6:11]

'world'

In [20]:
w[6:]

'world'

In [21]:
w[:5]

'Hello'

In [23]:
w[6:-2]

'wor'

In [25]:
w[::2]

'Hlowrd'

In [26]:
1 "+" 2

SyntaxError: invalid syntax (425102638.py, line 1)

In [27]:
'don\'t'

"don't"

In [29]:
str_a = "I love Python! "
str_b = "You too!"

print(str_a + str_b)

I love Python! You too!


In [30]:
x = 1
print("x = " + x)

TypeError: can only concatenate str (not "int") to str

In [31]:
print("x = " + str(x))

x = 1


In [32]:
w.upper()

'HELLO WORLD'

In [33]:
w.count("l")

3

In [39]:
w.replace("world", "Kharagpur")

'Hello Kharagpur'

In [40]:
name = "IIT Kharagpur"
country = 'India'

print("%s is a great school in %s!"%(name, country))

IIT Kharagpur is a great school in India!


In [41]:
print(f"{name} is a great school in {country}.")

IIT Kharagpur is a great school in India.


In [42]:
print(f"{3*4}")

12


In [43]:
# Lists

In [44]:
list_1 = [1, 2, 3]
list_1

[1, 2, 3]

In [45]:
list_2 = ['Hello', 'World']
list_2

['Hello', 'World']

In [46]:
list_3 = [1, 2, 3, 'Apple', 'orange']
list_3

[1, 2, 3, 'Apple', 'orange']

In [47]:
list_4 = [list_1, list_2]
list_4

[[1, 2, 3], ['Hello', 'World']]

In [48]:
list_3[2]

3

In [49]:
list_3[:3]

[1, 2, 3]

In [50]:
list_3[-1]

'orange'

In [51]:
list_4[0]

[1, 2, 3]

In [52]:
len(list_3)

5

In [53]:
list_1 + list_2

[1, 2, 3, 'Hello', 'World']

In [54]:
list_1.append(4)
list_1

[1, 2, 3, 4]

In [55]:
list_1.insert(2,'center')
list_1

[1, 2, 'center', 3, 4]

In [56]:
del list_1[2]
list_1

[1, 2, 3, 4]

In [57]:
list_5 = []
list_5.append(5)
list_5

[5]

In [58]:
list_5.append(6)
list_5

[5, 6]

In [59]:
5 in list_5

True

In [60]:
list('Hello World')

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']

In [61]:
# Tuples

In [62]:
tuple_1 = (1, 2, 3, 2)
tuple_1

(1, 2, 3, 2)

In [63]:
len(tuple_1)

4

In [64]:
tuple_1[1:4]

(2, 3, 2)

In [65]:
tuple_1.count(2)

2

In [67]:
list_1 = [1, 2, 3]
list_1[2] = 1
list_1

[1, 2, 1]

In [68]:
tuple_1[2] = 1

TypeError: 'tuple' object does not support item assignment

In [69]:
# a fruit list
['apple', 'banana', 'orange', 'pear']

['apple', 'banana', 'orange', 'pear']

In [70]:
# a list of (fruit, number) pairs
[('apple', 3), ('banana', 4) , ('orange', 1), ('pear', 4)]

[('apple', 3), ('banana', 4), ('orange', 1), ('pear', 4)]

In [71]:
a, b, c = list_1
print(a, b, c)

1 2 1


In [72]:
list_2 = 2, 4, 5
list_2

(2, 4, 5)

In [73]:
#Sets

In [74]:
{3, 3, 2, 3, 1, 4, 5, 6, 4, 2}

{1, 2, 3, 4, 5, 6}

In [75]:
set_1 = set([1, 2, 2, 3, 2, 1, 2])
set_1

{1, 2, 3}

In [76]:
set_2 = set((2, 4, 6, 5, 2))
set_2

{2, 4, 5, 6}

In [77]:
set('Banana')

{'B', 'a', 'n'}

In [78]:
print(set_1)
print(set_2)

{1, 2, 3}
{2, 4, 5, 6}


In [79]:
set_1.union(set_2)

{1, 2, 3, 4, 5, 6}

In [80]:
set_1.intersection(set_2)

{2}

In [81]:
set_1.issubset({1, 2, 3, 3, 4, 5})

True

In [82]:
# Dictionaries

In [83]:
dict_1 = {'apple':3, 'oragne':4, 'pear':2}
dict_1

{'apple': 3, 'oragne': 4, 'pear': 2}

In [84]:
dict_1['apple']

3

In [85]:
dict_1.keys()

dict_keys(['apple', 'oragne', 'pear'])

In [86]:
dict_1.values()

dict_values([3, 4, 2])

In [87]:
len(dict_1)

3

In [93]:
school_dict = {}
school_dict['IIT Kharagpur'] = 'India'
school_dict

{'IIT Kharagpur': 'India'}

In [94]:
school_dict['Oxford'] = 'UK'
school_dict

{'IIT Kharagpur': 'India', 'Oxford': 'UK'}

In [95]:
school_dict['UC Berkeley'] = 'USA'
school_dict

{'IIT Kharagpur': 'India', 'Oxford': 'UK', 'UC Berkeley': 'USA'}

In [96]:
dict([("UC Berkeley", "USA"), ('Oxford', 'UK')])

{'UC Berkeley': 'USA', 'Oxford': 'UK'}

In [98]:
"UC Berkeley" in school_dict

True

In [99]:
"Harvard" not in school_dict

True

In [100]:
list(school_dict)

['IIT Kharagpur', 'Oxford', 'UC Berkeley']

In [101]:
# introducing numpy arrays

In [102]:
import numpy as np

In [103]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [105]:
y = np.array([[1, 4, 3], [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [106]:
y.shape

(2, 3)

In [107]:
y.size

6

In [109]:
z = np.arange(1, 2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999], shape=(1999,))

In [110]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [111]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [112]:
x[1]

np.int64(4)

In [113]:
x[1:]

array([4, 3])

In [114]:
x[-1]

np.int64(3)

In [115]:
y[0, 1]

np.int64(4)

In [116]:
y[0, :]

array([1, 4, 3])

In [117]:
y[:, -1]

array([3, 7])

In [118]:
y[:, [0,2]]

array([[1, 3],
       [9, 7]])

In [119]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [120]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
np.empty(3)

array([3., 2., 1.])

In [122]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [123]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [124]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

In [125]:
a[1:4] = [9, 8, 7]
a

array([1, 9, 8, 7, 5, 6])

In [126]:
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 0] = 3
b[1, 1] = 4
b

array([[1., 2.],
       [3., 4.]])

In [127]:
b + 2

array([[3., 4.],
       [5., 6.]])

In [128]:
b - 2

array([[-1.,  0.],
       [ 1.,  2.]])

In [129]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [130]:
b / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [131]:
b ** 2

array([[ 1.,  4.],
       [ 9., 16.]])

In [132]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [133]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [134]:
b - d

array([[-2, -2],
       [-2, -2]])

In [135]:
b * d

array([[ 3,  8],
       [15, 24]])

In [136]:
b / d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [137]:
b**d

array([[   1,   16],
       [ 243, 4096]])

In [138]:
b.T

array([[1, 3],
       [2, 4]])

In [139]:
x = [1, 4, 9, 16]
np.sqrt(x)

array([1., 2., 3., 4.])

In [140]:
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [141]:
x > 3

array([False, False,  True,  True,  True, False])

In [142]:
x > y

array([ True, False,  True,  True,  True, False])

In [143]:
y = x[x > 3]
y

array([4, 5, 9])

In [144]:
x[x > 3] = 0
x

array([1, 2, 0, 0, 0, 3])