In [6]:
#Q1
import math

def my_sinh(x):
    y = (math.exp(x) - math.exp(-x)) / 2
    print(y)

In [7]:
my_sinh(0)

0.0


In [8]:
my_sinh(1)

1.1752011936438014


In [9]:
my_sinh(2)

3.626860407847019


In [28]:
#Q2 my checker board
# https://stackoverflow.com/questions/9671224/split-a-python-list-into-other-sublists-i-e-smaller-lists this was helpful

import numpy as np
def my_checker_board(n):
    l = []
    for i in range(n**2):
        if i % 2 == 0:
            l.append(1)
        if i % 2 == 1:
            l.append(0)
        l1 = [l[i:i + n] for i in range(0, len(l), n)]
    print(l1)

In [29]:
my_checker_board(1)

[[1]]


In [30]:
my_checker_board(2)

[[1, 0], [1, 0]]


In [31]:
my_checker_board(3)

[[1, 0, 1], [0, 1, 0], [1, 0, 1]]


In [27]:
my_checker_board(5)

[[1, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 1]]


In [14]:
#Q3
def my_triangle(b, h):
    a = 0.5*b*h
    print(a)

In [15]:
my_triangle(1, 1)

0.5


In [16]:
my_triangle(2, 1)

1.0


In [17]:
my_triangle(12, 5)

30.0


In [73]:
#Q4 my split matrix

def my_split_matrix(m):
    if len(m) % 2 != 0:
        n = (len(m) // 2) + 1
    else:
        n = len(m) // 2
    m1 = m[:, 0:n]
    m2 = m[:, n:]
    return m1, m2

In [74]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  

In [75]:
m1, m2 = my_split_matrix(m) 

In [78]:
m1

array([[1, 2],
       [4, 5],
       [7, 8]])

In [79]:
m2

array([[3],
       [6],
       [9]])

In [82]:
m = np.ones((5, 5))

In [85]:
m1, m2 = my_split_matrix(m)

In [86]:
m1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
m2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
#Q5

def my_cylinder(r, h):
    s = (2 * math.pi * (r**2)) + (2 * math.pi*r*h)
    v = math.pi * (r**2) *h
    print([s, v])

In [23]:
my_cylinder(1,5)

[37.69911184307752, 15.707963267948966]


In [24]:
my_cylinder(2,4)

[75.39822368615503, 50.26548245743669]


In [27]:
#Q6
import numpy as np

def my_n_odds(a):
    count = 0
    for i in a:
        if i%2 == 0:
            count += 0
        else:
            count += 1
    print(count)

In [28]:
my_n_odds(np.arange(100))

50


In [29]:
my_n_odds(np.arange(2, 100, 2))

0


In [32]:
#Q7 my_twos

def my_twos(m, n):
    mat = np.ones((m, n)) * 2
    print(mat)


In [33]:
my_twos(3, 2)

[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [34]:
my_twos(1, 4)

[[2. 2. 2. 2.]]


In [33]:
#Q8

my_subtractor = lambda x, y: x - y

print(my_subtractor(2, 4))

-2


In [59]:
#Q9

def add_string(s1, s2):
    if s2 == " ":
        return s1
    else:
        return s1 + " " + s2

In [60]:
s1 = add_string('Programming', ' ')

In [61]:
s2 = add_string('is', 'fun!')

In [62]:
type(s1)

str

In [63]:
add_string(s1, s2)

'Programming is fun!'

In [66]:
#Q10

def func(a):
    return a

x = func()
x

TypeError: func() missing 1 required positional argument: 'a'

In [75]:
def func(a):
return a

IndentationError: expected an indented block after function definition on line 1 (807121474.py, line 2)

In [76]:
# Q11

def greeting(name, age):
    print(f"Hi, my name is {name} and I am {age} years old.")

In [77]:
greeting('John', 26)

Hi, my name is John and I am 26 years old.


In [78]:
greeting('Kate', 19)

Hi, my name is Kate and I am 19 years old.


In [41]:
#Q12 donut area
import math
import numpy as np

def my_donut_area(r1, r2):
    a = r1 ** 2
    b = r2 ** 2
    result = math.pi * (b - a)
    print(result)

In [42]:
my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

[ 9.42477796 37.69911184 84.82300165]


In [83]:
#Q13

def my_within_tolerance(A, a, tol):
    output = []
    for i in range(len(A)):
        if abs(A[i] - a) < tol:
            output.append(i)
    print(output)

In [84]:
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

[1, 2]


In [85]:
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

[47, 48, 49, 50, 51, 52]


In [89]:
#Q14

def bounding_array(A, top, bottom):
    output = []
    for i in A:
        if bottom < i and i < top:
            i = i
            output.append(int(i))
        elif i <= bottom:
            i = bottom
            output.append(int(i))
        elif i >= top:
            i = top
            output.append(int(i))
    print(output)

In [90]:
bounding_array(np.arange(-5, 6, 1), 3, -3)

[-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]
